version: 0.2

env:
  shell: bash
  variables:
    AWS_REGION: "ap-northeast-1"

phases:
  build:
    commands:
      - docker build -t c18f-intern-app -f docker/php-apache/Dockerfile .
  post_build:
    commands:
      - docker push 280107060642.dkr.ecr.$AWS_REGION.amazonaws.com/c18f-intern-app
